
## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 971962245@qq.com #发送邮件的邮箱地址
    password:  xcapoytibhzqbdgh #客户端授权码，在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587
    from: 971962245@qq.com # 发送邮件的地址，和上面username一致
abc:
  config: 34567
